language: csharp
solution: assignment6/assignment6.sln
matrix:
  include:
    - dotnet: 2.1.502
      mono: none
      env: DOTNETCORE=2  # optional, can be used to take different code paths in your script
    - mono: latest
install:
- travis_retry nuget restore -source "https://www.nuget.org/api/v2" assignment6/assignment6.sln
  - nuget restore assignment6/assignment6.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release assignment6/assignment6.sln
  - mono ./testrunner/NUnit.Runners.3.9.0/tools/nunit-console3.exe ./MyProject.Tests/bin/Release/MyProject.Tests.dll