language: csharp
solution: assignment6.sln
install:
  - nuget restore assignment6.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
mono: none
dotnet: 2.1.502
script:
 - dotnet restore