language: csharp
solution: assignment6/assignment6.sln
install:
- travis_retry nuget restore -source "https://www.nuget.org/api/v2" assignment6/assignment6.sln
script:
- xbuild assignment6/assignment6.sln
- mono assignment6/packages/xunit.runner.console*/tools/xunit.console.exe assignment6/assignment6.Tests/bin/Debug/Fibonacci.Tests.dll